#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 IMG_FILE USER_DIR"
    exit 1
fi

set -e

# umount_retry DEVICE
function umount_retry {
    sync
    until umount $1
    do
        sleep 1
    done
}

# get_part_info start|size DISK_IMAGE PARTITION_NUMBER
function get_part_info {
    local cmd=$1
    local img_file=$2
    local part_no=$3

    val=`sfdisk -d $img_file | grep "^$img_file$part_no" | grep -oP "(?<=$cmd=)[ \\d+]*"`
    if [ "$?" -eq 0 ]; then
        echo "$(( ${val//[[:blank:]]/} * 512 ))"
    else
        return 1
    fi
}

function losetup_delete_retry {
    sync
    until losetup -d $1
    do
        sleep 1
    done

    # Wait a bit, weird race condition
    sleep 2
}


# losetup_partition DISK_IMAGE PARTITION_NUMBER
function losetup_partition {
    local part_start=$(get_part_info start $1 $2)
    local part_size=$(get_part_info size $1 $2)
    losetup -f --show --offset $part_start --sizelimit $part_size $1
}

img_name=$1
user_dir=$2

scion_dir="/home/scion/go/src/github.com/netsec-ethz/scion"
openvpn_dir="/etc/openvpn"

# Mount rootfs partition
lodev=$(losetup_partition $img_name 2)
partprobe $lodev
echo "Mounting root partition on $lodev..."
mount -t ext4 $lodev mnt/

echo "Deleting previous file"
rm -rf "mnt/$scion_dir/gen"
rm -rf "mnt/$openvpn_dir/client.conf"

echo "Copying new files"
rsync -o -g --quiet --archive --specials --hard-links --acls --xattrs --sparse "$user_dir/gen" "mnt/$scion_dir/"
cp "$user_dir/client.conf" "mnt/$openvpn_dir/client.conf"
chmod 600 "mnt/$openvpn_dir/client.conf"

echo "Unmount image"
umount_retry mnt
losetup_delete_retry $lodev

echo "Compressing image"
lbzip2 -zk $img_name
