#!/usr/bin/env bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 ROOTFS USER_DIR INPUT_IMAGE"
    exit 1
fi

set -e

rootfs_dir=$1
user_dir=$2
img_file=$3

scion_dir="/home/scion/go/src/github.com/netsec-ethz/scion"
openvpn_dir="/etc/openvpn"

# Mount rootfs partition

echo "Deleting previous file"
rm -rf "$rootfs_dir/$scion_dir/gen"
rm -rf "$rootfs_dir/$openvpn_dir/client.conf"

echo "Copying new files"
rsync -o -g --quiet --archive --specials --hard-links --acls --xattrs --sparse "$user_dir/gen" "$rootfs_dir/$scion_dir/"
cp "$user_dir/client.conf" "$rootfs_dir/$openvpn_dir/client.conf"
chmod 600 "$rootfs_dir/$openvpn_dir/client.conf"

sync

# echo "Compressing image"
lbzip2 -zk --fast $img_file

echo "Done!"
