#!/usr/bin/env bash
set -e

#
# NOTE: This script is run within the chroot after second stage debootstrap!
#

# Make sure we are chrooted
if [ "$(stat -c %d:%i /)" = "$(stat -c %d:%i /proc/1/root/.)" ]; then
	echo "Something went wrong and we aren't in a chroot, to save your system from damage the script will fail and exit now."
	exit 1;
fi

if [ "$#" -lt 5 ]; then
	echo "Usage: $0 LOCALE UNAME UPASS RPASS INC_REC"
	exit 1
fi

LOCALE=$1
UNAME=$2
UPASS=$3
RPASS=$4
INC_REC=$5

echo "Running postinstall script..."

# Sanitize environnement
LC_ALL=C
LANG=C

# Make dpkg/apt-get noninteractive
export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true
export LC_ALL=C LANGUAGE=C LANG=C
export FLASH_KERNEL_SKIP=1

# Prevent apt-get from starting services
echo "#!/bin/sh
exit 101
" > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

# Set the locale
echo "LANG=${LOCALE}" >> /etc/default/locale
echo "LC_ALL=C" >> /etc/default/locale
echo "LC_CTYPE=C" >> /etc/default/locale

echo "locales locales/default_environment_locale select ${LOCALE}" | debconf-set-selections
echo "locales locales/locales_to_be_generated select ${LOCALE} UTF-8" | debconf-set-selections

# Finish multistrap
# /var/lib/dpkg/info/base-passwd.preinst install
# /var/lib/dpkg/info/dash.preinst install
dpkg --force-all --configure debconf 2>/dev/null || true
dpkg --force-all --configure mawk 2>/dev/null || true
dpkg --configure -a

# Make sure all apt keys are installed
cd /apt-keys > /dev/null
# for i in *.asc; do
# 	apt-key --keyring /etc/apt/trusted.gpg.d/${i%.*}.gpg add ${i}
# done
cd - > /dev/null

# Set root password
echo "root:${RPASS}" | chpasswd

# Add user $UNAME
useradd -m ${UNAME} -s /bin/bash

# Set $UNAME password
echo "${UNAME}:${UPASS}" | chpasswd

# Add $UNAME to sudo group
adduser ${UNAME} sudo || true
adduser ${UNAME} audio || true
adduser ${UNAME} video || true
adduser ${UNAME} input || true
adduser ${UNAME} tty || true

echo "----- 1 -----"
echo "Adding Google DNS to resolv.conf"
echo "nameserver 8.8.8.8" > /etc/resolv.conf;

echo "----- 2 -----"
apt-get update

echo "----- 3 -----"
APTOPTS="-y --assume-yes --force-yes"
if [ "$INC_REC" == "0" ]; then
	APTOPTS="$APTOPTS --no-install-recommends";
fi

echo "----- 4 -----"
# Install extra packages
cat /packages.txt
if [ -f /packages.txt ]; then
	apt-get $APTOPTS install $(cat /packages.txt);
fi

echo "----- 5 -----"
# Run custom install scripts
if [ -d /postinst ]; then
	echo "----- Running custom postinst root scripts -------"
	for i in `find /postinst -maxdepth 1 -type f -executable -not -name "*~" | sort`; do
		echo "  Running $i"
		$i ${UNAME}
	done
else
	echo "No custom postinst scripts found"
fi
echo "----- 6 -----"
if [ -d /postinstusr ]; then
	echo "----- Running custom postinst USR scripts -------"
	for i in `find /postinstusr -maxdepth 1 -type f -executable -not -name "*~" | sort`; do
		echo "  Running $i"
		su -c $i - ${UNAME}
	done
else
	echo "No custom postinst scripts found"
fi

echo "----- 7 -----"
# Re-enable services to start
rm -f /usr/sbin/policy-rc.d

# Cleanup
echo "Running clean up"
rm -f /etc/ssh/ssh_host_*
apt-get autoclean
apt-get clean
dpkg --clear-avail
