#!/usr/bin/env bash

set -e

echo "Running ODROID custom script to remove unnecessary services..."
echo "Removing cups"
apt-get -y --assume-yes --force-yes autoremove cups
apt-get -y --assume-yes --force-yes autoremove cups-*

echo "avahi daemon"
apt-get -y --assume-yes --force-yes autoremove avahi-daemon
apt-get -y --assume-yes --force-yes autoremove avahi-dnsconfd