#!/usr/bin/env bash

echo "Running user script as $USER"

wget https://raw.githubusercontent.com/netsec-ethz/scion-coord/master/scion_install_script.sh

chmod +x scion_install_script.sh

./scion_install_script.sh -p "/install_files/scion/patches" -a ~/.bash_aliases

# Lets enable services
sudo systemctl enable scion.service
sudo systemctl enable scion-viz.service

# We don't need this anymore
rm scion_install_script.sh
