#!/usr/bin/env bash

set -e

echo "Running user script as $USER"

wget https://gist.githubusercontent.com/xabarass/7aa560a2ba9010d8dbb6f08029509ae5/raw/03a57e662165a191d4e9ac6d5822ddf2e472ed11/scion_install_script.sh

chmod +x scion_install_script.sh

./scion_install_script.sh -p "/install_files/scion/patches" -a ~/.bash_aliases

# Lets enable services
sudo systemctl enable scion.service
sudo systemctl enable scion-viz.service

# We don't need this anymore
rm scion_install_script.sh
